export default [
  {
    id: 1,
    title: "Title 1",
    imageLink: "",
    description: "This is the description for project 1",
    technologies: [
      { type: "react" },
      { type: "MUI" },
      { type: "MySQL" },
      { type: ".NET" },
    ],
    publicFacing: false,
  },
  {
    id: 2,
    title: "Title 2",
    imageLink: "",
    description: "",
    technologies: [],
    publicFacing: true,
    siteLink: "",
  },
  {
    id: 3,
    title: "Title 3",
    imageLink: "",
    description: "",
    technologies: [],
    publicFacing: false,
  },
  {
    id: 4,
    title: "Title 4",
    imageLink: "",
    description: "",
    technologies: [],
    publicFacing: true,
    siteLink: "",
  },
];
